XKNX/xknxproject

- pyproject.toml
- test/zip/test_extractor.py
- xknxproject/loader/application_program_loader.py
- xknxproject/loader/group_address_loader.py
- xknxproject/loader/hardware_loader.py
- xknxproject/loader/loader.py
- xknxproject/loader/location_loader.py
- xknxproject/loader/topology_loader.py
- xknxproject/zip/extractor.py
Use pathlib.Path for path definitions and tempfile.TemporaryDirectory to create a temporary directory for unzipping. 
I'll address the pylint error (`consider-using-with`) from `TemporaryDirectory` in another PR - so the extractor can be used only as context manager.
closes #36
> use pathlib.Path and tempfile.TemporaryDirectory

- README.md
- pyproject.toml
- requirements_production.txt
- setup.py
- xknxproject/loader/application_program_loader.py
- xknxproject/loader/hardware_loader.py
- xknxproject/loader/project_loader.py
- xknxproject/models/knxproject.py
- xknxproject/models/models.py
- xknxproject/xml/parser.py
This saves even more memory (on my personal project now 16.6 instead of 18.8 MB) and is slightly faster (1.49 sec).
We can also remove a dependency as ElementTree is in Pythons standard library.
Some adaptions to the models and attribute extraction had to be made as `Element.get()` returns `Optional[str]` (instead of lxml's `etree.Element.get()` which returned `Any`).
> Use ElementTree instead of lxml

- xknxproject/loader/hardware_loader.py
- xknxproject/loader/project_loader.py
- xknxproject/models/models.py
- xknxproject/xml/parser.py
Previously we used `ParameterInstanceRefs` to construct a `ApplicationProgramRefID` (filename). This was not always correct, and some DeviceInstances had no ParameterInstanceRefs.
Closes #14
> Load all/correct application program for each device

- xknxproject/loader/application_program_loader.py
This speeds up parsing my personal project from 1.61 to 0.64 seconds 🚀 
We currently only need `ComObject` and `ComObjectRef`. Both are children of the `Static` tag - so when the end of that tag is reached we may close the file.
> Skip parsing unused tags from application programs

- test/conftest.py
- test/resources/stubs/xknx_test_project.json
- xknxproject/models/__init__.py
- xknxproject/models/knxproject.py
- xknxproject/models/models.py
- xknxproject/xml/parser.py
Communication objects can be used from either group addresses or devices.
An example to get a list of communication objects for a specific device:
```py
project: KNXProject
device_ia = "1.1.10"
[project["communication_objects"][com_id] for com_id in project["devices"][device_ia]["communication_object_ids"]]
```
> Store communication objects in root key and link to them from group addresses and devices

- test/resources/stubs/xknx_test_project.json
- xknxproject/loader/project_loader.py
- xknxproject/models/knxproject.py
- xknxproject/models/models.py
- xknxproject/xml/parser.py
Humble addition to include the Description field of group addresses.
This can be useful to use the Description field in ETS to add formatted text that can then be used by an import script to build the hass entities.
Example uses of the Description field:
- add a tag to indicate the group address should or not be imported into hass
- add non gaddr parameters, like cover travelling_time_down or travelling_time_up
> Import description for group addresses

- .coveragerc
`coverage run -m pytest` now works.
Previously it errored with 
> CoverageWarning: Module ets was never imported. (module-not-imported)
Latest PR (#186) had no Codecov comment so I had a look at it. There was an upload, but it is still processing in Codecov.
It seems to have worked fine previously in CI, but I'm not sure why it worked or if this fix changes something about that.
> Fix coverage source directory

- .github/workflows/ci.yml
- .github/workflows/pre-commit-update.yml
- Don't run CI workflow twice on PRs
- Add pre-commit updater workflow
same as we do in `xknx` repo.
> Update CI workflows

- .coveragerc
- test/resources/stubs/module-definition-test.json
- test/resources/stubs/xknx_test_project.json
- test/test_knxproj.py
- test/xml/test_parser.py
- xknxproject/loader/application_program_loader.py
- xknxproject/loader/hardware_loader.py
- xknxproject/models/models.py
- xknxproject/xknxproj.py
- xknxproject/xml/parser.py
Use device address instead of application ref id as first part of key for communication objects, so similar references eg. from 2 common devices or devices using modules don't overwrite previously parsed communication object.
Closes #189
> Use unique keys for communication objects (Module and multiple instance compatibility)

- test/resources/stubs/module-definition-test.json
- test/resources/stubs/xknx_test_project.json
- xknxproject/loader/hardware_loader.py
- xknxproject/loader/project_loader.py
- xknxproject/models/__init__.py
- xknxproject/models/knxproject.py
- xknxproject/models/models.py
- xknxproject/xml/parser.py
- Support devices with multiple application versions
these have different `Hardware2ProgramRefId` in a common `Hardware` tag. So the resolution of `Product` and `Hardware2Program` tags is now done with the RefIds from `DeviceInstance` instead of forging a `HardwareRefId` for the `Hardware` tag.
- rename Device product_name to hardware_name 
`name` is product_name
- fix Device descriptions
these have just been a copy of `hardware_name` (which was mixed up with product_name down the stack 🙃)
> Support devices with multiple application versions

- test/resources/stubs/module-definition-test.json
- test/resources/stubs/xknx_test_project.json
- xknxproject/models/knxproject.py
- xknxproject/xml/parser.py
`"name"` seems to be some internal identifier not shown in ETS, but I guess it's ok to preserve that too.
Module-devices seem to resolve their text templates in their `ComObjectInstanceRef` in the project file - which means we don't have to care about that and they are already translated 😃
> Preserve text, description and function text of COs

- test/resources/stubs/module-definition-test.json
- test/resources/stubs/xknx_test_project.json
- test/test_knxproj.py
- xknxproject/loader/application_program_loader.py
- xknxproject/loader/hardware_loader.py
- xknxproject/models/knxproject.py
- xknxproject/models/models.py
- xknxproject/xknxproj.py
- xknxproject/xml/parser.py
Translate
- hardware product names
- communication object information
Add number and object_size to communication objects.
Translation is based on given a language_code. If `None`, the default language will be used.
```py
knxproj: XKNXProj = XKNXProj(
archive_name="test.knxproj",
archive_password="test",
language_code="de-DE",
)
```
This increases parsing time (on my personal project) by ~~25~~ ~22% and peak memory usage by ~5%.
```
Py 3.10         Py 3.11
before                1.31 sec        1.22 sec
scalene           20.199 MB       20.189 MB
fil               13.3 MiB        14.5 MiB
language_code=None    1.30 sec        1.22 sec
scalene           20.311 MB       20.189 MB
fil               13.3 MiB        14.5 MiB
language_code="de-DE" 1.58 sec        1.49 sec
scalene …
```
> Apply translations

- test/resources/stubs/module-definition-test.json
- test/resources/stubs/xknx_test_project.json
- xknxproject/xml/parser.py
"1/2/3" instead of "GA-2" for easier lookup from xknx telegrams and better readability
> Use group address strings instead of RefIds as keys

- test/resources/stubs/module-definition-test.json
- test/resources/stubs/xknx_test_project.json
- xknxproject/loader/project_loader.py
- xknxproject/models/knxproject.py
- xknxproject/models/models.py
- xknxproject/xml/parser.py
These are integers that are unique project wide.
They could become handy for migrations to new versions or updated project data at some point.
> Add project_uid for group addresses and devices

- test/test_knxproj.py
- xknxproject/loader/knx_master_loader.py
- xknxproject/xknxproj.py
- xknxproject/xml/parser.py
Parse language codes from knx_master.xml and add fall back to match by language only - ignoring country code. So "De" or "de-AT" would both resolve to language code "de-DE".
Rename "language_code" parameter to "language" in `XKNXProj` to avoid mix-up.
> Fuzzy match language code

- test/resources/stubs/module-definition-test.json
- test/resources/stubs/xknx_test_project.json
- xknxproject/loader/project_loader.py
- xknxproject/models/__init__.py
- xknxproject/models/knxproject.py
- xknxproject/models/models.py
- xknxproject/xml/parser.py
- xknxproject/zip/extractor.py
`version` key is moved to `xknxproject_version` in `info`. 
`language_code` is also moved into `info`.
```json
{
"info": {
"project_id": "P-080F",
"name": "ModuleDefinitionTest",
"last_modified": "2023-04-11T21:06:02.8735147Z",
"group_address_style": "ThreeLevel",
"guid": "26520acd-6231-4fe4-a409-4d1610e7a251",
"created_by": "ETS5",
"schema_version": "20",
"tool_version": "5.7.1428.39779",
"xknxproject_version": "2.1.0",
"language_code": "de-DE"
},
```
> Parse project infos to `info` key

- README.md
- xknxproject/xknxproj.py
use `path` instead of `archive_name` as we expect the project file path here.
"Archive" may be confusing if one doesn't know internals of `.knxproj` files - especially since there are also `.knxprojarchive` files created by ETS which we don't support.
> Simplify parameters names of XKNXProj

- test/resources/stubs/module-definition-test.json
- test/resources/stubs/xknx_test_project.json
- test/test_util.py
- xknxproject/loader/application_program_loader.py
- xknxproject/loader/project_loader.py
- xknxproject/models/knxproject.py
- xknxproject/models/models.py
- xknxproject/util.py
- xknxproject/xml/parser.py
Communication objects can have multiple valid DPTs so their key `dpt: DPTType | None` is changed to `dpts: list[DPTType]`.
GroupAddresses seem to only support a single DPT so they aren't changed.
> Parse a list of all DPTs of a communication object instead of just the last DPT

- .pre-commit-config.yaml
- requirements_testing.txt
flake8 plugins and pydocstyle are superseded by ruff.
pytest-icdiff provides nice assertion diffs
> Remove flake8 plugins and add pytest-icdiff

- xknxproject/xml/parser.py
Skip orphaned `ComObjectInstanceRef` pointing only to non-existent `GroupAddress Id`.
It seems that this can happen with ETS 5.7.7 and MDT JAL-0810M.02 Shutter actuators.
fixes https://github.com/XKNX/knx-frontend/issues/71
> Ignore orphaned communication object instances

- tox.ini
This avoids having tox to build the package for every environment anew.
On my machine this reduces time tox needs to run from 32 seconds to 11 🚴💨
> Reuse universal wheel for all tox environments

- pyproject.toml
- requirements_production.txt
- xknxproject/zip/extractor.py
I had issues trying to build a Docker image form linux/arm/v7 that runs a http server using your library. This was due to the fact that cryptography does not have prebuilt binaries for armv7, and it needs to be compiled during he pip install phase.
Problem is that it also needs a rust compiler to do so (as cryptography uses rust), and after trying for two days, I was not able to install it in the image and buid cryptography in the image. 
Also cryptography is only used in a small portion of the code, and I figured switching to hashlib will lead to an improved cross architecture compatibily and improve my own workflow (which is cross compiling docker images) but also, and I hope, others workflow.
> Replace cryptography with hashlib

- xknxproject/xml/parser.py
for better readability.
- Order of methods resembles execution order
- Internal functions and methods are prefixed with `_`
- Helper functions moved out of XMLParser class
- Use more dict comprehensions
- Use recursive conversion also for top level
> Restructure parser module

- test/resources/stubs/module-definition-test.json
- test/resources/stubs/test_project-ets4.json
- test/resources/stubs/xknx_test_project.json
- xknxproject/loader/application_program_loader.py
- xknxproject/loader/project_loader.py
- xknxproject/models/__init__.py
- xknxproject/models/knxproject.py
- xknxproject/models/models.py
- xknxproject/xml/parser.py
This adds a channel identifier to communication objects and channel informations (currently only name) to devices.
`"name": "Kanal {{ChNo}}: Wohnzimmer"` this should read "Kanal A: Wohnzimmer"
> Parse device channels

- test/resources/stubs/module-definition-test.json
- test/resources/stubs/test_project-ets4.json
- test/resources/stubs/xknx_test_project.json
- xknxproject/models/knxproject.py
- xknxproject/models/models.py
- xknxproject/xml/parser.py
- Add application program identifier to devices
- Add application program identifier and module information to communication objects
Communication objects with same application program, module definition and root number can probably be configured in the same way as they very likely represent similar values only for different channels or physical outlets.
> Add application program identifier and module information

- test/resources/stubs/module-definition-test.json
- test/resources/stubs/test_project-ets4.json
- test/resources/stubs/xknx_test_project.json
- xknxproject/loader/hardware_loader.py
- xknxproject/models/knxproject.py
- xknxproject/models/models.py
- xknxproject/xml/parser.py
Add order number to devices for comparability of hardware product across different application versions.
> Add order number to devices

- test/resources/stubs/module-definition-test.json
- test/xml/test_parser.py
- xknxproject/loader/application_program_loader.py
- xknxproject/models/__init__.py
- xknxproject/models/models.py
- xknxproject/xml/parser.py
- Parse Allocators and ModuleDef argument Allocates
- Move data merging from xml loader to dataclass method
- Parse communication object numbers from allocators (as fallback if not set as ObjNumberBase argument value)
fixes #361
> Parse communication object numbers of modules from allocators

- test/test_util.py
- xknxproject/loader/application_program_loader.py
- xknxproject/loader/project_loader.py
- xknxproject/models/__init__.py
- xknxproject/models/models.py
- xknxproject/util.py
if not found in project data (0.xml).
> Inherit channel name from application channel

- xknxproject/exceptions/__init__.py
- xknxproject/exceptions/exceptions.py
- xknxproject/loader/project_loader.py
- xknxproject/models/models.py
This avoids `TypeError: StopIteration interacts badly with generators and cannot be raised into a Future` and provides (hopefully) actionable error messages.
> Better error messages on StopIteration errors

- xknxproject/const.py
- xknxproject/zip/extractor.py
ETS 4.1.6 (Build 3250) seems to use the same schema version as 4.1 (Version 11), but the `knx_master.xml` lacks the `<?xml version="1.0" encoding="UTF-8"?>` first line. So we have to check first and second line for the namespace (we skipped first line previously).
> Support ETS 4.1 project files

- xknxproject/loader/project_loader.py
Schema 14 doesn't use `Links` attribute in `ComObjectInstanceRef` - it uses ETS 4 style here. 
`Links` seem to be used in Schema versions 20+
> Correctly parse Schema 14 device links
